In [2]:
import os 
import json
import numpy as np

parent_directory = os.path.dirname(os.getcwd()) 
file = os.path.join(parent_directory, "object_index", 'contact_plane_object.json')
with open(file) as f:
    file_dir = json.load(f)
file_dir = file_dir['test_dataset']
file_dir = [f[:-5] for f in file_dir]
test_file_dir = list(set(file_dir))

operations = {}

# 循環處理每個文件名，提取物品名稱並初始化字典
for filename in test_file_dir:
    # 將標準化後的名稱用來初始化計數
    operations[filename] = {"total": 0, "successful": 0}

for item, data in operations.items():
    print(item, data)
    break

Mustard_1.0 {'total': 0, 'successful': 0}


In [3]:

pred_grasps_cam = np.load(os.path.join(parent_directory, 'results/pred_grasps_cam.npy'), allow_pickle=True)
print(pred_grasps_cam.shape)
if len(pred_grasps_cam) == 0:
    print("No grasps found")


(0,)
No grasps found


In [8]:
sg_pcd = np.load(os.path.join(parent_directory, 'multiview_data/pc_segments_combine.npy'), allow_pickle=True)
sg_noise_pcd = np.load(os.path.join(parent_directory, 'multiview_data/pc_segments_combine_noise.npy'), allow_pickle=True)
print(sg_pcd.shape)
print(sg_pcd[0].shape)
print(sg_pcd)

(3, 3)
(3,)
[[-0.12225409  0.45464666  0.14785567]
 [-0.12225409  0.45464666  0.14785567]
 [-0.12225409  0.45464666  0.14785567]]
